name: CRC Replenisher

on:
  schedule:
    # Runs every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: read

jobs:
  replenish:
    runs-on: ubuntu-latest
    if: vars.JOB_ENABLED == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10
      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: "20"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run replenisher
        env:
          CRC_SAFE_KEY: ${{ secrets.CRC_SAFE_KEY }}
          CRC_PROFILE: ${{ secrets.CRC_PROFILE }}
          MAX_FLOW_THRESHOLD: ${{ vars.MAX_FLOW_THRESHOLD }}
          RPC_URL: ${{ secrets.RPC_URL }}
        run: pnpm start
